#! /bin/sh


OS_NAME=$(uname -s)
CONFIG_DIR=~/.config
CONFIG_APPS="nvim fish ranger"

function install_homebrew() {
    if [ $OS_NAME = 'Darwin' ] && ! which -s brew; then
        /usr/bin/ruby -e \
            "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew bundle install
    fi
}


install_homebrew

# make .config directory
test -d $CONFIG_DIR || mkdir $CONFIG_DIR

for app in $CONFIG_APPS; do

    echo "Stowing $app into $CONFIG_DIR/$app"
    mkdir -p $CONFIG_DIR/$app
    ./stow -t $CONFIG_DIR/$app -S $app
done

