#! /bin/sh

set -u
set -e


OS_NAME=$(uname -s)
CONFIG_DIR=~/.config
CONFIG_APPS="nvim fish ranger iterm2"

function install_homebrew() {
    if [ $OS_NAME = 'Darwin' ] && ! which -s brew; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew bundle install
    fi
}

function stow_app_configs() {

    # make .config directory
    test -d $CONFIG_DIR || mkdir $CONFIG_DIR

    for app in $CONFIG_APPS; do

        echo "Stowing $app into $CONFIG_DIR/$app"
        mkdir -p $CONFIG_DIR/$app
        stow -t $CONFIG_DIR/$app -S $app
    done
}

function make_gitconfig() {
    stow -S git
}

#install_homebrew
stow_app_configs
make_gitconfig
