#!/bin/sh

WORKDIR=$(cd "$(dirname "$0")" "$0" && pwd) DOTFILES=$(cd "$WORKDIR/.." & pwd)
stow_app_configs() {
	CONFIG_DIR="$HOME/.config"
	CONFIG_APPS="nvim fish ranger"

	# make .config directory
	test -d "$CONFIG_DIR" || mkdir "$CONFIG_DIR"

	for app in $CONFIG_APPS; do

		echo "Stowing $app into $CONFIG_DIR/$app"
		mkdir -p "$CONFIG_DIR/$app"
		stow -t "$CONFIG_DIR/$app" -S "$app"
	done
}

include_gitconfig() {
	git config --global include.path "$DOTFILES/git/gitconfig-public"
}

nvim_plug_install() {
	nvim -E +PlugInstall +qall
}

chsh_fish() {
	sudo chsh -s $(which fish) $(whoami)
}

if [ "$(uname -s)" = "Darwin" ]; then
	"$WORKDIR/bootstrap-macos"
elif [ -f /etc/debian_version ]; then
	"$WORKDIR/bootstrap-debian"
fi


stow_app_configs
include_gitconfig
nvim_plug_install
chsh_fish

echo "=======Done======="
