#!/bin/sh

WORKDIR=$(cd "$(dirname "$0")" "$0" && pwd)

stow_app_configs() {
	CONFIG_DIR="$HOME/.config"
	CONFIG_APPS="nvim fish ranger"

	# make .config directory
	test -d "$CONFIG_DIR" || mkdir "$CONFIG_DIR"

	for app in $CONFIG_APPS; do

		echo "Stowing $app into $CONFIG_DIR/$app"
		mkdir -p "$CONFIG_DIR/$app"
		stow -t "$CONFIG_DIR/$app" -S "$app"
	done
}

stow_gitconfig() {
    stow -t "$HOME" -S git
}

if [ "$(uname -s)" = "Darwin" ]; then
	"$WORKDIR/bootstrap-macos"
elif [ -f /etc/debian_version ]; then
	"$WORKDIR/bootstrap-debian"
fi


echo "=======Done======="
