#!/bin/bash


sudo apt-get update

# Instructions from https://github.com/neovim/neovim/wiki/Installing-Neovim#appimage-universal-linux-package
install_neovim() {
	curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
	chmod u+x nvim.appimage

	./nvim.appimage --appimage-extract
	./squashfs-root/AppRun --version

	mv squashfs-root /
	ln -s /squashfs-root/AppRun /usr/bin/nvim
}

install_neovim_support() {
	sudo pip3 install neovim
}

install_latest_fish() {
	echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /' \
		| sudo tee /etc/apt/sources.list.d/shells:fish:release:3.list
	curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key \
		| gpg --dearmor \
		| sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
	sudo apt update
	sudo apt-get install -y --no-install-recommends fish
}

install_tools() {
	sudo apt-get install -y --no-install-recommends \
		bat \
		fasd \
		fd-find \
		fzf \
		jq \
		npm \
		rbenv \
		ripgrep \
		shellcheck \
		stow \
		tmux \

}

install_yarn() {
	# yarn now installed with corepack
	npm install -g corepack
}



install_neovim
install_neovim_support
install_tools
install_latest_fish
