#!/bin/sh

# Create a session named 'hidden' if it doesn't exist. If created

tmux has-session -t hidden 2>/dev/null ||
  (TMUX_TMP=$TMUX
  unset TMUX
  tmux new-session -d -s hidden "sh -ic 'sleep 1'"
  export TMUX=$TMUX_TMP)
tmux join-pane -s $1 -t hidden
tmux break-pane -t $1
